version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/control"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - docker

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - github-actions
