#!/usr/bin/env python3
"""Render a Compose override with one MinerU worker container per GPU slot.

Each container pins a physical GPU with device_ids. The NVIDIA runtime remaps
that card to index 0 inside the container, so CUDA_VISIBLE_DEVICES stays 0.
Several containers may share one device_ids value: each process loads its own
MinerU engine. Raising GPU_WORKER_CONCURRENCY does not, because one process
serializes parses on a single engine.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

MAX_GPU_COUNT = 64
MAX_WORKERS_PER_GPU = 32
PROFILE = "mineru-multi-gpu"


def parse_positive_int(raw: str, name: str, maximum: int) -> int:
    try:
        value = int(raw)
    except ValueError as exc:
        raise SystemExit(f"{name} must be an integer, got {raw!r}") from exc
    if value < 1 or value > maximum:
        raise SystemExit(f"{name} must be between 1 and {maximum}, got {value}")
    return value


def render_compose(gpu_count: int, workers_per_gpu: int) -> str:
    """Return a Compose YAML document for gpu_count * workers_per_gpu workers."""
    lines = [
        "# Generated by docker/render-gpu-workers.py. Do not edit.",
        "#",
        f"# GPUs: {gpu_count}",
        f"# Workers per GPU: {workers_per_gpu}",
        f"# Profile: {PROFILE}",
        "#",
        "# Do not also enable profile mineru-gpu (the single shared worker).",
        "# CUDA_VISIBLE_DEVICES is 0 because device_ids remaps the selected",
        "# card to index 0 inside the container.",
        "",
        "x-mineru-gpu-worker: &mineru-gpu-worker",
        "  image: mineru-worker:latest",
        "  build:",
        "    context: ..",
        "    dockerfile: docker/Dockerfile.worker",
        "    args:",
        "      PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.org/simple}",
        "  restart: always",
        "  depends_on:",
        "    redis:",
        "      condition: service_healthy",
        "      required: false",
        "  env_file:",
        "    - ../.env",
        "  volumes:",
        "    - mineru_output:/tmp/mineru_output",
        "    - mineru_temp:/tmp/mineru_temp",
        "    - ../worker:/app/worker",
        "    - ../shared:/app/shared",
        "  networks:",
        "    - mineru-network",
        "",
        "services:",
    ]
    for gpu_index in range(gpu_count):
        for slot in range(workers_per_gpu):
            service = f"mineru-worker-gpu-{gpu_index}-{slot}"
            worker_name = f"mineru-gpu-{gpu_index}-{slot}"
            lines.extend(
                [
                    f"  {service}:",
                    "    <<: *mineru-gpu-worker",
                    f'    profiles: ["{PROFILE}"]',
                    f"    container_name: {service}",
                    "    environment:",
                    "      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}",
                    "      - PIP_INDEX_URL=${PIP_INDEX_URL:-https://pypi.org/simple}",
                    "      - CUDA_VISIBLE_DEVICES=0",
                    f"      - WORKER_NAME={worker_name}",
                    "      - WORKER_CONCURRENCY=${GPU_WORKER_CONCURRENCY:-1}",
                    "    deploy:",
                    "      resources:",
                    "        reservations:",
                    "          devices:",
                    "            - driver: nvidia",
                    f'              device_ids: ["{gpu_index}"]',
                    "              capabilities: [gpu]",
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gpu-count", required=True)
    parser.add_argument("--workers-per-gpu", required=True)
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Write the Compose file here. Default: stdout.",
    )
    args = parser.parse_args(argv)
    gpu_count = parse_positive_int(args.gpu_count, "MINERU_GPU_COUNT", MAX_GPU_COUNT)
    workers_per_gpu = parse_positive_int(
        args.workers_per_gpu, "MINERU_WORKERS_PER_GPU", MAX_WORKERS_PER_GPU
    )
    document = render_compose(gpu_count, workers_per_gpu)
    if args.output is None:
        sys.stdout.write(document)
    else:
        args.output.write_text(document, encoding="utf-8")
        print(
            f"Wrote {args.output} ({gpu_count * workers_per_gpu} workers)",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
